### ISSUE TITLE
[12.0][IMP] base_tier_validation, ability to auto start validation

### ISSUE THREAD

**Issue by kittiu** [OCA/server-ux#100]
Based on current feature, user will need to click on "Request Validation" to start the validation flow.
I would like to request the feature to auto trigger "Request Validation" when a certain condition of the document is met. 
cc @lreficent @ps-tubtim

**Comment by LoisRForgeFlow** [comment]
I'm not really sure about this, it can add more complexity for something that maybe is best to do with automated actions, what do you think?

**Comment by kittiu** [comment]
@lreficent you are right. Until the benefit is justified, automated action is enough ;)
Thank you!

**Comment by LoisRForgeFlow** [comment]
@jbeficent @etobella any second thought here?

**Comment by kittiu** [comment]
Currently, all tiers for all models mixed in the tree view.
My propose if any, is to have new model/view act as the header of tiers grouping it for a  single model / use cases. Then we can have a place to configure anything, i.e., auto triggering.
