### ISSUE TITLE
[11.0] Test failing in base_import_security_group module

### ISSUE THREAD

**Issue by LoisRForgeFlow** [OCA/server-ux#104]
[Latest travis builds are failing](https://travis-ci.org/OCA/server-ux/jobs/608332238#L973), see last commit in branch 11.0: 3ccf2269d34b77e0565c4d1408fdb195c97af5b5

cc @alejandrosantana @antespi as contributors of the module you may have a better idea of what can be happening, could you have a look? Thanks!

**Comment by LoisRForgeFlow** [comment]
cc @espo-tony @i-vyshnevska you participated in the latest migrations to v10 and v11, you coul also have some clue.

**Comment by i-vyshnevska** [comment]
doesn't look like a problem in module base_import_sequrity_group like in https://travis-ci.org/OCA/server-ux/builds/607053202?utm_source=github_status&utm_medium=notification test for that addon pass successfully, when on next commit 3ccf226 they fail, 
I am wondering why that commit has two travis builds? the failed looks like it were run under other than root user, or security file wasn't initialized

**Comment by LoisRForgeFlow** [comment]
Maybe is some change that was introduced in how travis is run since that module is merged until now?

cc @moylop260 @pedrobaeza any idea?

**Comment by moylop260** [comment]
Hi @lreficent 
Maybe a change from other dependencies since that last travis build is green:
 - https://travis-ci.org/OCA/server-ux/builds/616601890

So, it was fixed.
Regards!
