### ISSUE TITLE
[12.0][IMP] base_tier_validation_formula, ability to use both Domain and Formula.

### ISSUE THREAD

**Issue by kittiu** [OCA/server-ux#114]
@hveficent @lreficent @ps-tubtim 
One of the goal to do is to use base_tier_validation in the way that, i.e., for purchase.order, different Operating Unit or Department, will use different set of Tier Validation.
At first, I was thinking that we need to create another addon, like, base_tier_validation_dept.

But after playing around the "Domain" is coming in handy. For example, we can [('department', '=', 'Dept-A')]. That is easy.

But currently, if we use "Formula", the domain will be disabled by default and allow only Formula. Although we can write code to select only required department, but I think it is quite difficult.

My idea is that, can we allow use both together? So, once install `base_tier_validation_formula` we can have definition options,
* Domain
* Formula
* **Domain & Formula**

Says, there are 100 POs, the domain filter by department which reduce it to 40 POs, **then** formula will work on that 40 POs only.

This should be a small enhancement to `base_tier_validation_formula`, and won't affect the existing one.

Note: 
* This should be good with the helper (domain is on header) we are working on too.

What do you think? If you ok, we will do the PR.

**Comment by LoisRForgeFlow** [comment]
Hi @kittiu 

This sounds reasonable to me, and as you said it will not affect existing installations. So, you can go ahead and open a PR, we'll be glad to review it.

**Comment by kittiu** [comment]
Thank you, @ps-tubtim let's do it :+1:

**Comment by nmoturi** [comment]
Hi,

How is this module functionality different from base_exception...? other than technical implementation..?

**Comment by LoisRForgeFlow** [comment]
Feature implemented in v12 and 13, closing.

**Comment by LoisRForgeFlow** [comment]
@nmoturi This is not he place for that question, use the forums instead, but... have you even tried the modules before asking?
