### ISSUE TITLE
What is the one.label means in ir_exports_line.py?

### ISSUE THREAD

**Issue by HengzheLi** [OCA/server-ux#120]
https://github.com/OCA/server-ux/blob/5ff570ca35ed01679dd0c9ccfbecff31b419fc18/base_export_manager/models/ir_exports_line.py#L164

I debug the code using importing case, every time, I breakpoint here, the value of one.label always False, so the ValidateError exception always is thrown. 

I can't get the point of checking the one.label. Can anyone explain this? Thanks

**Comment by pedrobaeza** [comment]
It's a way to check if the field really exists.

**Comment by HengzheLi** [comment]
Then I think I encountered a bug.
I init ir.exports.line using csv file ir.exports.line.csv with below content
```
id,export_id/id,"name"
export_website_name,export_website_page,"name"
export_website_url,export_website_page,"url"
```
I upgraded my custom module to apply above data. But I always got ValidationError: Field 'name'  does not exist and Field 'url' does not exist.
It seems like that it will check model ir.exports.line if has name property and url property using this code:
```
if not one.label:
```
And obviously, one.label always is False. Because ir.exports.line never have name and url properties

**Comment by pedrobaeza** [comment]
I'm afraid the problem is in the way you are doing that. If you do it via UI, there's no problem.

**Comment by HengzheLi** [comment]
OK. It might be. But it seems that ir.exports.line could not import from UI. It only can be editted manually.
However, it the logic is wrong in this case, could it be fixed or could you tell me how to workaround it if I want to init the data during setup odoo? I can do it by myself

**Comment by HengzheLi** [comment]
After I sync the latest Odoo source code then run my case again, the issue gone.....
