### ISSUE TITLE
[12] Error when importing date_range-12 add-on

### ISSUE THREAD

**Issue by PhilippeRaven** [OCA/server-ux#124]
I'm currently trying to import the date_range module for Odoo 12, using the web GUI on the configuration page > "Import module".
But when I try to import it, I got this error : 
`Error while importing module 'date_range': "Module loading date_range failed: file /tmp/tmpouueqfn4/date_range/security/ir.model.access.csv could not be processed:\n No matching record found for external id 'model_date_range' in field 'Object'\nNo matching record found for external id 'model_date_range_type' in field 'Object'\nNo matching record found for external id 'model_date_range' in field 'Object'\nNo matching record found for external id 'model_date_range_type' in field 'Object'\nMissing required value for the field 'Object' (model_id)\nMissing required value for the field 'Object' (model_id)\nMissing required value for the field 'Object' (model_id)\nMissing required value for the field 'Object' (model_id)"`

If you can help, thanks :)

**Comment by pedrobaeza** [comment]
That option is only for importing theme modules (specifically, modules with only data and without code), not the rest of the existing modules. You must do it other way.

**Comment by PhilippeRaven** [comment]
Exact ! Thanks for this, I did import it in another way, it works, thanks :)
