### ISSUE TITLE
[13.0] Tier validation subtype of messages

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/server-ux#125]
```
def _notify_accepted_reviews(self):
def _notify_rejected_review(self):
```

both these methods use subtype="mt_comment" which I think is incorrect. 

In for example a purchase order workflow we don't want to send a message to the supplier of the PO (which also follower) if a PO is internally rejected or approved.

I suggest I create a PR to change the subtype to mt_note.

@LoisRForgeFlow

**Comment by LoisRForgeFlow** [comment]
I fully agree, could you open a PR addressing it?
