### ISSUE TITLE
[12.0][base_tier_validation] Validation Date not show timezone

### ISSUE THREAD

**Issue by Saran440** [OCA/server-ux#130]
Testing with hr_expense_tier_validation module -> https://github.com/OCA/hr/tree/12.0/hr_expense_tier_validation

When I Validation or Reject, Field Validation Date will show datetime not timezone.
![Selection_008](https://user-images.githubusercontent.com/20896369/75320826-1c3e1b80-58a2-11ea-8035-bd87b91ce957.png)
and I setting admin timezone is Asia/Bangkok (+07 GTM). It should be 14:12:06.
![Selection_009](https://user-images.githubusercontent.com/20896369/75320926-51e30480-58a2-11ea-8adc-828ca60e66cf.png)

**Comment by LoisRForgeFlow** [comment]
@Saran440 can you open a PR addressing this?

**Comment by Saran440** [comment]
@LoisRForgeFlow Yes, I can but I don't know how to fix. Do you have idea how to fix?

**Comment by brenoalef** [comment]
Is there an estimate for when this will be merged?

**Comment by kittiu** [comment]
@LoisRForgeFlow @brenoalef can you guys help move this forward? I think this is a good fix can be deployed to all other version easily.

Note: I also have another fix for approve_sequence problem waiting, but better have minor bugs cleared first.

Thank you all!
