### ISSUE TITLE
[12.0, 13.0][BUG] base_tier_validation_formula, error if no python code.

### ISSUE THREAD

**Issue by kittiu** [OCA/server-ux#137]
Currently, when we use definition type = formula, or domain_formula, but user didn't type in python code. When create document, error as following,

![image](https://user-images.githubusercontent.com/1973598/76591103-db8d0600-6521-11ea-83c7-809276bc1cc0.png)

This is because it try to evaluate False or the default code which is,
```
# Available locals:
#  - rec: current record
```
But in this case no code should mean True.

cc @ps-tubtim

**Comment by LoisRForgeFlow** [comment]
Fixes merged for v12 and v13.
