### ISSUE TITLE
[13.0] Tier validation not working multicompany

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/server-ux#140]
Model "tier.review" doesn't contain company_id and no record rule is active, when switching companies a record rule error is raised because the tier is loaded but the underlaying record is not visible for the user.

The idea I have now:
- Add company_id to tier.review company_id = fields.Many2one(related='definition_id.company_id', store=True)
- Add record rule on tier_definition
- Filter reviews in review_user_count on company

@LoisRForgeFlow What do you think?

**Comment by LoisRForgeFlow** [comment]
It makes sense, my only concern would be the (unlikely) possibility of a document without company_id, nowadays almost every document in odoo has it but we need to cover every use case.

If you are brave enough you can try to make a PR, if not I would try to find some time for this in the following weeks.

**Comment by CasVissers-360ERP** [comment]
@LoisRForgeFlow 
For me a PR to fix it is a bit out of my league. I will definitely help functionally with a PR though.

**Comment by CasVissers-360ERP** [comment]
@LoisRForgeFlow 
I did some work on this:
1. Added a field 
```
    company_id = fields.Many2one(
        comodel_name="res.company",
        compute='_compute_company_id',
        store=True)
```
2. Add method to compute:
  ```
  @api.depends('model', 'res_id')
    def _compute_company_id(self):
        for rec in self:
            model = self.env[rec.model]
            rel_rec = model.search(
                    [("id", "=", rec.res_id)],
                    limit=1)
            if rel_rec and 'company_id' in model._fields:
                rec.company_id = rel_rec.company_id
            else:
                rec.company_id = None
```
3.  update review_user_count to filter on company:
 ```
   @api.model
    def review_user_count(self):
        user_reviews = {}
        to_review_docs = {}
        **company = self.env.company**
        for review in self.env.user.**sudo().**review_ids.filtered(
            lambda r: r.status == "pending" **and r.company_id.id in company.ids**
        ):
```

My problem is that we have to inherit all modules with models we want to search on. Any suggestions to avoid this?

EDIT: 
And of-course also added a record rule:
```
    <record id="tier_review_comp_rule" model="ir.rule">
        <field name="name">Tier Review multi-company</field>
        <field name="model_id" ref="model_tier_review"/>
        <field name="domain_force"> ['|',('company_id', 'in', company_ids),('company_id','=',False)]</field>
    </record>
```

**Comment by LoisRForgeFlow** [comment]
Solved
