### ISSUE TITLE
[13.0]mass_editing domain in fields

### ISSUE THREAD

**Issue by ValentinVinagre** [OCA/server-ux#142]
Hi,
I don't understand why the 'field_id' field have 'read_only = false' in its domain. Could @legalsylvain explain me this change?

https://github.com/OCA/server-ux/blob/9a7a80210f2defdf8ebc3acb133300c8447c47e3/mass_editing/models/mass_editing_line.py#L26

Thanks a lot,

**Comment by legalsylvain** [comment]
because if readonly is set to True, so the field should not be edited. So not be mass edited.

**Comment by ValentinVinagre** [comment]
Hi @legalsylvain ,
but Odoo have a lot of 'readonly' fields and if we can't change the value of that..... it's an important limitation.

Don't you think so?

**Comment by pedrobaeza** [comment]
Not only that... sometimes the technique is to put readonly the field, but readonly=False in the view (or according certain criteria), so you can't impose that limitation.

**Comment by legalsylvain** [comment]
> Not only that... sometimes the technique is to put readonly the field, but readonly=False in the view (or according certain criteria), so you can't impose that limitation.

OK. never seen that implementation, but no problem.

@ValentinoDefelice feel free to propose a PR.

**Comment by pedrobaeza** [comment]
> OK. never seen that implementation, but no problem.

Well, it's the usual way Odoo implements it:

https://github.com/odoo/odoo/blob/6dff3024d19c9dd44c71992469540e3f09dd3247/addons/sale/models/sale.py#L156

You have pong incorrect user.

**Comment by legalsylvain** [comment]
@pedrobaeza : thanks for the link.

@ValentinVinagre : could you make a PR ?

**Comment by ValentinVinagre** [comment]
I can try it, but tomorrow 👍
