### ISSUE TITLE
[RFO] V12.0 - V13.0 base_search_custom_field_filter --> Group by?

### ISSUE THREAD

**Issue by HaraldPanten** [OCA/server-ux#156]
Hi all,

I was wondering about the possibility to enhance/make a new module complementing base_search_custom_field_filter, but I'm not sure if that would be possible or not.

As you've been working on it just few days ago, and probably you remember how you developed this, do you think that having a similar structure as base_search_custom_field_filter could be possible for "group by" functionality instead?

Could you give me two pieces of advice as how do you think we should start working on it? Any clue?

Do you think this would be a useful feature for OCA?

IMO, it could be useful for "grouping by" some use cases.

Do you think a kind of "web_advanced_group_by", just like --> "https://github.com/OCA/web/tree/13.0/web_advanced_search " would be better instead?

Thanks!

**Comment by pedrobaeza** [comment]
Not possible. Group by can't be done for fields outside the same table (and must be stored thus).

**Comment by HaraldPanten** [comment]
Thanks Pedro.

Closing issue
