### ISSUE TITLE
[12.0] Unable to reject record when review type is set to expression

### ISSUE THREAD

**Issue by Taar** [OCA/server-ux#168]
I've only tested this in version 12.0 but it might also be an issues in other versions.

OCA modules required to reproduce this issue:
- `purchase-workflow/purchase_request`
- `purchase-workflow/purchase_request_tier_validation`
- `server-ux/base_tier_validation`
- `server-ux/base_tier_validation_formula`

Assuming you have two users named, `User1` and `User2`. Both users also need to have access to the `purchase_request` module.

### To reproduce:
- Create a tier definition with the following:
    - Referenced Model: Purchase Request
    - Validated By: Python Expression
    - Python Expression: `rec.env['res.users'].search([('name', '=', 'User2')])`
    - Definition: Domain
    - Definition Domain: Match all records
- Login with `User1` create a new Purchase Request and click on the Request Validation button
- Login with `User2`, navigate to the newly created purchase request and click on the Reject button.

### Expected:
The purchase request should be rejected

### What's happening:
Nothing. When the reviewer clicks on the `Reject` button nothing happens.

### Details:
At first I thought this might be a bug with the `purchase_request_tier_validation` module. However, after digging around, I've discovered that it's an issue with the rejection code in the `base_tier_validation` modules.

I'll be submitting a PR with my solution to this problem but I would like some feedback on my approach as I'm new to Odoo development.

The issue lies with the `_rejected_tier` method on the `tier.validation` model. When it filters the review records it only checks the user against the review record's `reviewer_id` and `reviewer_group_id` which are only set when the review type is `individual` or `group` (See [here](https://github.com/oca/server-ux/blob/12.0/base_tier_validation/models/tier_validation.py#L270)). It should instead be checking if the current user is in `reviewer_ids` like the validation method `_validate_tier` does (See [here](https://github.com/oca/server-ux/blob/12.0/base_tier_validation/models/tier_validation.py#L180)).

**Comment by brenoalef** [comment]
I'm facing the same issue. It'd be great to have this merged.
