### ISSUE TITLE
[13.0] barcode_action: android browser unavailable

### ISSUE THREAD

**Issue by snowtianyou** [OCA/server-ux#172]
Code scanning does not trigger_ Barcodehandleaction event

**Comment by pedrobaeza** [comment]
Which module? Which Odoo version? Steps to reproduce the problem?

**Comment by bealdav** [comment]
Hi @pedrobaeza 

https://help.github.com/en/github/building-a-strong-community/manually-creating-a-single-issue-template-for-your-repository
https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

could probably save your time ;-)

**Comment by pedrobaeza** [comment]
@bealdav I have it as saved reply, so not too much time, but yes, I agree we can have a issue template. Anyway, it doesn't matter. Who don't to put details, they ignore that template. I see it on odoo/odoo. And they get the expected result: to get ignored as well.

**Comment by snowtianyou** [comment]
odoo13 Community Edition    barcode_action apps

 var ActionBarcodeField = AbstractField.extend({
        init: function () {
            this._super.apply(this, arguments);
            this.trigger_up('activeBarcode', {
                name: this.name,
                commands: {
                    barcode: '_barcodeHandleAction',
                },
                value:alert("haha")
            });
        },

    });

**Comment by pedrobaeza** [comment]
Steps to reproduce the problem? Which is the problem?

**Comment by CasVissers-360ERP** [comment]
I think I can actually confirm this issue, on our Zebra barcode scanner running Android the barcode scan is not used as input in the wizard. The barcode scan doesn't seem to trigger anything.

**Comment by pedrobaeza** [comment]
We still don't know which module of this repository.

**Comment by CasVissers-360ERP** [comment]
barcode_action :)

**Comment by frankvogler** [comment]
Elaborating on Cas' comment:

Odoo 13.0+e on odoo.sh
barcode_action module

**Issue:**
Barcode/keyboard input is not received/processed using Android devices. Tested with:
- Zebra TC210K, Android 10
- OnePlus Nord, Android 11
- Barcode scanner input 
- Keyboard input
- Chrome browser (on Android)
- Odoo Android app

None of these combinations of tests trigger any action. Input for both keyboard and barcode scanner is tested in Sales app to verify input is working (see video 2). 

**Steps to reproduce:**
- input value using barcode_action from Android device with either barcode scanner or keyboard, either in Odoo app or Chrome browser. Nothing happens.

**Video 1:** Working functional sample test on Chrome/Windows 10 - https://drive.google.com/file/d/1qXfnZNFSVoiCpSGsYK-dqKNkBvoRQFzO/view

**Video 2:** Not working test on Zebra/Android - https://drive.google.com/file/d/1dkUnyByVGD0Fk09NlPYQATvVDyXeNh5-/view
(the end where nothing is happening is me frantically scanning the barcode with the Zebra device. No result at all.)

Hope this helps.

**Comment by CasVissers-360ERP** [comment]
@etobella 
Do you maybe have an idea in what direction we could search? 

@AdriaGForgeFlow @fshah-initos 
You both migrated the module. Any ideas?

**Comment by etobella** [comment]
Did it work on 12.0? How are you reading the barcode? Does it work with a standard odoo barcode reader widget?

**Comment by CasVissers-360ERP** [comment]
We tried the widget="barcode_handler", same result, this is the one you mean right? We will try 12.0 after the runbot build has finished. Maybe it's unrelated to the module but just a core Odoo issue.

We are reading the barcode using a Zebra TC21.
