### ISSUE TITLE
[12.0][mass_editing] Error while updating from 12.0.1.0.0 to 12.0.1.1.0

### ISSUE THREAD

**Issue by mowny** [OCA/server-ux#190]
When trying to Update via Apps, I get the following error:

> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/home/odoo12/odoo/odoo/models.py", line 1108, in _validate_fields
>     check(self)
>   File "/home/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 351, in _check_xml
>     self.postprocess_and_fields(view.model, view_doc, view.id)
>   File "/home/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 1096, in postprocess_and_fields
>     self.raise_view_error(message, view_id)
>   File "/home/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
>     raise ValueError(message)
> ValueError: Das Feld `group_ids` existiert nicht
> 
> Fehler Kontext:
> Ansicht `mass.object.form`
> [view_id: 3326, xml_id: mass_editing.view_mass_object_form, model: mass.object, parent_id: k. A.]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/odoo12/odoo/odoo/tools/convert.py", line 758, in parse
>     self._tags[rec.tag](rec, de, mode=mode)
>   File "/home/odoo12/odoo/odoo/tools/convert.py", line 663, in _tag_record
>     record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
>   File "/home/odoo12/odoo/odoo/models.py", line 3838, in _load_records
>     data['record']._load_records_write(data['values'])
>   File "/home/odoo12/odoo/odoo/models.py", line 3776, in _load_records_write
>     self.write(values)
>   File "/home/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 444, in write
>     return super(View, self).write(self._compute_defaults(vals))
>   File "/home/odoo12/odoo/odoo/models.py", line 3347, in write
>     fields[0].determine_inverse(records)
>   File "/home/odoo12/odoo/odoo/fields.py", line 1117, in determine_inverse
>     getattr(records, self.inverse)()
>   File "/home/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
>     view.write(data)
>   File "/home/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 444, in write
>     return super(View, self).write(self._compute_defaults(vals))
>   File "/home/odoo12/odoo/odoo/models.py", line 3321, in write
>     self._write(store_vals)
>   File "/home/odoo12/odoo/odoo/models.py", line 3457, in _write
>     self._validate_fields(vals)
>   File "/home/odoo12/odoo/odoo/models.py", line 1112, in _validate_fields
>     raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
> odoo.exceptions.ValidationError: ('Fehler während der Constraint-Validierung\n\nDas Feld `group_ids` existiert nicht\n\nFehler Kontext:\nAnsicht `mass.object.form`\n[view_id: 3326, xml_id: mass_editing.view_mass_object_form, model: mass.object, parent_id: k. A.]', None)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/odoo12/odoo/odoo/http.py", line 654, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/home/odoo12/odoo/odoo/http.py", line 312, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/home/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
>     raise value
>   File "/home/odoo12/odoo/odoo/http.py", line 696, in dispatch
>     result = self._call_function(**self.params)
>   File "/home/odoo12/odoo/odoo/http.py", line 344, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/home/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/home/odoo12/odoo/odoo/http.py", line 337, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/home/odoo12/odoo/odoo/http.py", line 939, in __call__
>     return self.method(*args, **kw)
>   File "/home/odoo12/odoo/odoo/http.py", line 517, in response_wrap
>     response = f(*args, **kw)
>   File "/home/odoo12/odoo/addons/web/controllers/main.py", line 962, in call_kw
>     return self._call_kw(model, method, args, kwargs)
>   File "/home/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/home/odoo12/odoo/odoo/api.py", line 749, in call_kw
>     return _call_kw_multi(method, model, args, kwargs)
>   File "/home/odoo12/odoo/odoo/api.py", line 736, in _call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "<decorator-gen-67>", line 2, in button_immediate_upgrade
>   File "/home/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
>     return method(self, *args, **kwargs)
>   File "/home/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 622, in button_immediate_upgrade
>     return self._button_immediate_function(type(self).button_upgrade)
>   File "/home/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
>     modules.registry.Registry.new(self._cr.dbname, update_module=True)
>   File "/home/odoo12/odoo/odoo/modules/registry.py", line 86, in new
>     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
>   File "/home/odoo12/odoo/odoo/modules/loading.py", line 417, in load_modules
>     force, status, report, loaded_modules, update_module, models_to_check)
>   File "/home/odoo12/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
>     perform_checks=perform_checks, models_to_check=models_to_check
>   File "/home/odoo12/odoo/odoo/modules/loading.py", line 222, in load_module_graph
>     load_data(cr, idref, mode, kind='data', package=package, report=report)
>   File "/home/odoo12/odoo/odoo/modules/loading.py", line 68, in load_data
>     tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
>   File "/home/odoo12/odoo/odoo/tools/convert.py", line 802, in convert_file
>     convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
>   File "/home/odoo12/odoo/odoo/tools/convert.py", line 865, in convert_xml_import
>     obj.parse(doc.getroot(), mode=mode)
>   File "/home/odoo12/odoo/odoo/tools/convert.py", line 764, in parse
>     exc_info[2]
>   File "/home/odoo12/odoo/odoo/tools/pycompat.py", line 86, in reraise
>     raise value.with_traceback(tb)
>   File "/home/odoo12/odoo/odoo/tools/convert.py", line 758, in parse
>     self._tags[rec.tag](rec, de, mode=mode)
>   File "/home/odoo12/odoo/odoo/tools/convert.py", line 663, in _tag_record
>     record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
>   File "/home/odoo12/odoo/odoo/models.py", line 3838, in _load_records
>     data['record']._load_records_write(data['values'])
>   File "/home/odoo12/odoo/odoo/models.py", line 3776, in _load_records_write
>     self.write(values)
>   File "/home/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 444, in write
>     return super(View, self).write(self._compute_defaults(vals))
>   File "/home/odoo12/odoo/odoo/models.py", line 3347, in write
>     fields[0].determine_inverse(records)
>   File "/home/odoo12/odoo/odoo/fields.py", line 1117, in determine_inverse
>     getattr(records, self.inverse)()
>   File "/home/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
>     view.write(data)
>   File "/home/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 444, in write
>     return super(View, self).write(self._compute_defaults(vals))
>   File "/home/odoo12/odoo/odoo/models.py", line 3321, in write
>     self._write(store_vals)
>   File "/home/odoo12/odoo/odoo/models.py", line 3457, in _write
>     self._validate_fields(vals)
>   File "/home/odoo12/odoo/odoo/models.py", line 1112, in _validate_fields
>     raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
> odoo.tools.convert.ParseError: "Fehler während der Constraint-Validierung
> 
> Das Feld `group_ids` existiert nicht
> 
> Fehler Kontext:
> Ansicht `mass.object.form`
> [view_id: 3326, xml_id: mass_editing.view_mass_object_form, model: mass.object, parent_id: k. A.]
> None" while parsing /home/odoo12/custom/addons-extra/mass_editing/views/mass_editing_view.xml:4, near
> <record model="ir.ui.view" id="view_mass_object_form">
>         <field name="name">mass.object.form</field>
>         <field name="model">mass.object</field>
>         <field name="arch" type="xml">
>             <form string="Object">
>                 <sheet>
>                     <div class="oe_button_box" name="buttons">
>                         <field name="ref_ir_act_window_id" invisible="1"/>
>                         <button name="create_action" type="object" string="Add Sidebar Button" class="oe_inline oe_stat_button" attrs="{'invisible':[('ref_ir_act_window_id','!=',False)]}" icon="fa-plus" help="Display a button in the sidebar of related documents to open a composition wizard"/>
>                         <button name="unlink_action" type="object" string="Remove Sidebar Button" class="oe_stat_button" icon="fa-minus" attrs="{'invisible':[('ref_ir_act_window_id','=',False)]}" help="Remove the contextual action to use this template on related documents" widget="statinfo"/>
>                     </div>
>                     <div class="oe_title">
>                         <label for="name" class="oe_edit_only"/>
>                         <h1>
>                             <field name="name" required="1"/>
>                         </h1>
>                     </div>
>                     <group>
>                         <group name="model_id">
>                             <field name="model_id" required="1" attrs="{'readonly':[('ref_ir_act_window_id','!=',False)]}"/>
>                         </group>
>                         <group name="model_list">
>                             <field name="model_list" invisible="1"/>
>                         </group>
>                     </group>
>                     <notebook colspan="4">
>                         <page string="Fields">
>                             <field name="field_ids" colspan="4" nolabel="1" domain="[('ttype', 'not in', ['reference', 'function']), ('mass_editing_domain', 'in', model_list)]"/>
>                         </page>
>                         <page string="Security">
>                             <field name="group_ids" nolabel="1"/>
>                         </page>
>                         <page string="Advanced" attrs="{'invisible':[('ref_ir_act_window_id','=',False)]}">
>                             <group colspan="2" col="2">
>                                 <field name="ref_ir_act_window_id"/>
>                             </group>
>                         </page>
>                     </notebook>
>                 </sheet>
>             </form>
>         </field>
>     </record>

Are there additional dependencies? If so, which?

**Comment by pedrobaeza** [comment]
You haven't updated the module in your DB. Please do it.

**Comment by mowny** [comment]
> You haven't updated the module in your DB. Please do it.

Which one of the buttons was that again?

**Comment by pedrobaeza** [comment]
By command line, `.../odoo -u mass_editing --stop-after-init`. On UI (if you can login), press the "Update" button on the module.

**Comment by mowny** [comment]
Okay, that "Upgrade" button worked without the error after the _second_ run of `odoo/odoo-bin -d OUR_DATABASE -u mass_editing --stop-after-init`.
Thank you very much for your help!

###### and odoo's app updating process is 👎

**Comment by pedrobaeza** [comment]
Yes, please don't use that section... We even have a module for removing it: https://github.com/OCA/server-brand/tree/12.0/disable_odoo_online
