### ISSUE TITLE
Installing error: AttributeError: module 'odoo.api' has no attribute 'multi'

### ISSUE THREAD

**Issue by alch7607** [OCA/server-ux#208]
I get this error when installing Date_range in Odoo Community v13. Can someone please help me?

**Comment by simahawk** [comment]
very likely you are using an old version of the module. `api.multi` is not available on v13.
See https://github.com/OCA/server-ux/tree/13.0/date_range

**Comment by iobbbbbbbbbh** [comment]
you can remove the decorator  @api.multi then it will start working

**Comment by heriipurnama** [comment]
remove
