### ISSUE TITLE
[12.0] Base Tier Validation - Validation Date with Timezone

### ISSUE THREAD

**Issue by patrickrwilson** [OCA/server-ux#249]
The validation date seems to show in UTC so is it possible to show it in the user's time instead?

To show this, I created a record and validated it about a minute later. In the screenshot below you can see when the test record was created which shows 12:55:22 but the validation shows 19:56:57 even though it was just a few min later.
![image](https://user-images.githubusercontent.com/36892066/102261562-75ca1200-3ed7-11eb-9a12-3e2f0c5c598d.png)

This is confusing users so I was wondering if anyone knows how we can make the datetime show similar to other fields in Odoo?

**Comment by kittiu** [comment]
Is this the fix needed?
https://github.com/OCA/server-ux/pull/206

cc @Saran440

**Comment by patrickrwilson** [comment]
Actually, this seems to already be fixed as I just tested the latest and it seemed to work correctly. Thanks @kittiu, you pointed me to the place to look for that piece of code. 
I think we are still running an older version that is missing that part so i'll work on getting it updated. I'm closing this issue.

Thanks again.
