### ISSUE TITLE
[12.0] base_tier_validation: test fails when purchase_tier_validation is in the same repo

### ISSUE THREAD

**Issue by yostashiro** [OCA/server-ux#250]
This test https://github.com/OCA/server-ux/blob/30e3e035889fc9b7f461c4de70d9f26b78df9402/base_tier_validation/tests/test_tier_validation.py#L155-L160 fails in CI when purchase_tier_validation (or any of those xxx_tier_validation modules) is in the same repo.

**Comment by pedrobaeza** [comment]
We remove such test in #181 for 13.0 due to the same problem.
