### ISSUE TITLE
[14.0] date_range custom search date range criteria are not shown

### ISSUE THREAD

**Issue by petrus-v** [OCA/server-ux#289]
Custom date range that i've manually configured are not add to the custom filter when I try add custom filter on a date field.

## To reproduce:

* go to date range configuration
* add date range type called "TEST"
* add date ranges for this new type
* go to any list view
* create a custom filter on "create at" field

## current behaviour:

"in TEST" is not present in the list of possible values

## epexected:

"in TEST" as a possible criteria

## impact version

14.0

## analyse

I've done few investigations, as far I understand, [web.search_filters in v13](https://github.com/odoo/odoo/blob/13.0/addons/web/static/src/js/views/control_panel/search/search_filters.js) moved to [web.CustomFilterItem in v14](https://github.com/odoo/odoo/blob/14.0/addons/web/static/src/js/control_panel/custom_filter_item.js) and this module still overload [web.search_filters component](https://github.com/OCA/server-ux/blob/14.0/date_range/static/src/js/date_range.js#L6)

**Comment by petrus-v** [comment]
@feketemihai I'm wondering if the odoo change happen before or after #217 ?

I don't expect to fix it right now, I was testing the feature but do not require it right now.

**Comment by feketemihai** [comment]
@petrus-v check #314

**Comment by pedrobaeza** [comment]
It should be fixed now.

**Comment by petrus-v** [comment]
Thanks for reference and issue monitoring :eyes: 

I confirm it's works on runbot :+1:
