### ISSUE TITLE
[14.0] base_tier_validation_server_action : error when set "Post Reject Action" in tier validation

### ISSUE THREAD

**Issue by SurachetS** [OCA/server-ux#292]
step to error

setup tier validation
![image](https://user-images.githubusercontent.com/15519988/109134583-c50aa980-7788-11eb-8c2b-b038392aff8d.png)

server action for reject
![image](https://user-images.githubusercontent.com/15519988/109134655-da7fd380-7788-11eb-9583-2514a2890e38.png)

when rejecting in PR
![image](https://user-images.githubusercontent.com/15519988/109134697-e5d2ff00-7788-11eb-959f-f26805e77247.png)

@kittiu what do you think?

**Comment by kittiu** [comment]
Have you get the latest code of base_tier_validation after this fix?
https://github.com/OCA/server-ux/pull/283

**Comment by kittiu** [comment]
@SurachetS is this resolved for you?

**Comment by SurachetS** [comment]
> @SurachetS is this resolved for you?

Yes, the state field is currently modified, so I have to allow state field in _get_under_validation_exceptions().

**Comment by kittiu** [comment]
Please close this issue if all works for you. Thanks!

**Comment by SurachetS** [comment]
ok, thank you
