### ISSUE TITLE
[IMP] base_tier_validation, allow "Inactive" for unused tier.definition

### ISSUE THREAD

**Issue by kittiu** [OCA/server-ux#307]
Currently, if a tier.definition of a document is not used, we can delete it. -> this leave all in-validation document a mess.

In real world, it is common that, approval process is changed on a cut off date. Allowing inactive status of tier.definition can keep the old definition for the old documents.

WDYT?

**Comment by LoisRForgeFlow** [comment]
What is wrong with the active field?

**Comment by kittiu** [comment]
> What is wrong with the active field?

I wasn't see field on UI, it saw it now. Thanks!
