### ISSUE TITLE
[14.0] Date range - Filter not working correctly

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/server-ux#328]
See video:
https://drive.google.com/file/d/1S2B-dz8vLypn2B-aZUHI9AMp7xQJCDv5/view

When applying a filter the filter is converted to a different date range.

@astirpe @len-foss

**Comment by len-foss** [comment]
Hey @CasVissers-360ERP  :-)
You may have meant to ping someone else, I never even used this module.
Anyway, I solved it at https://github.com/OCA/server-ux/pull/329, if you want to apply locally you can just add a `parseInt`.
