### ISSUE TITLE
[14.0] Mass editing configured but does not show fields

### ISSUE THREAD

**Issue by asm8073** [OCA/server-ux#392]
I've created a server action with the "Mass Edit Records" as the action and has choosen one field for update contacts. 
Then, when I try to use the action on a set of records, I see the module pop-up shown, biut I do not see the field to set. I only see the number of lines to update, the OK andd the Cancel actions. 
Could you give a hint why it could not work ?

**Comment by pedrobaeza** [comment]
You have to add fields to edit in the list in the mass editing definition. For further help, please submit your question in forums.

**Comment by asm8073** [comment]
Hi,
As I said in my report, I added one field with mass editing in the action definition to be able to edit it in the pop-up. But I cannot see it. What else could be the problem here ? Do you need more information to see the issue ?

**Comment by pedrobaeza** [comment]
Well, that are the steps. Reproduce the problem in OCA runbot (there's a link in the README), and if so, link it to this report.

**Comment by HaraldPanten** [comment]
> Hi, As I said in my report, I added one field with mass editing in the action definition to be able to edit it in the pop-up. But I cannot see it. What else could be the problem here ? Do you need more information to see the issue ?

Once you add a mass edition option in the action button, remember that probably you have to refresh your browser to reload the view. If you have no permission restrictions for this mass edition, and you followed the correct configuration steps you'll see the option in the action button 👍
