### ISSUE TITLE
server-ux repo should publish modules to OCA wheelhouse

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/server-ux#4]
I can see that the modules in server-ux are not being pushed to https://wheelhouse.odoo-community.org/oca

We are starting to use Wheelhouse in our deployments.

**Comment by JordiBForgeFlow** [comment]
Sorry, it is working-.

**Comment by sebalix** [comment]
Hi Jordi,
I know you were using Buildout, did you manage to install wheels with it? (maybe with the `buildout.wheel` extension?)

**Comment by JordiBForgeFlow** [comment]
@sebalix we're replacing buildout now. using pip + docker seems to be better for us.
See https://github.com/Eficent/medical-spain-requirements as an example of a procedure to install an odoo + OCA modules using pip.

It does not cover the part of configuration of the odoo-server.conf, but we plan to manage that within the docker config.

**Comment by sebalix** [comment]
Ok, thank you!
