### ISSUE TITLE
[base_tier_validation] Reviewer should have read access, even for document he/she don't have access.

### ISSUE THREAD

**Issue by kittiu** [OCA/server-ux#415]
**Is your feature request related to a problem?**
For strict security organization, in many case user A don't have access to a document (no read). But he is assigned as tier reviewer to that document. He is not allowed to review the document (security message will show when reviewer tray icon is loaded)

**Describe the solution you'd like**
As a reviewer, he/she should be able to click the document from reviewer tray, and make the review.

I think this read access, should be assigned without the need of the ACL. In other words, as soon as the document has his/her name in the reviewer table below, he/she should have read access. And the read access may be removed after the document is approved, or rejected.

@etobella @LoisRForgeFlow have you ever have this kind of security blocking problem in real life project before?

**Comment by kittiu** [comment]
Opinion,

If we don't want to fix in the core code (models.py), to allow such thing. We will need to add security rule like this 
 to the model in `<models>_tier_validation`

```
    <record id="ir_rule_<model>_allowed_reviewers" model="ir.rule">
        <field name="model_id" ref="model_<mode>" />
        <field name="domain_force">[('review_ids.reviewer_ids', 'in', [user.id])]</field>
        <field name="name">Budget Request Tier Reviewer</field>
        <field name="groups" eval="[(4, ref('base.group_user'))]" />
        <field eval="0" name="perm_unlink" />
        <field eval="0" name="perm_write" />
        <field eval="1" name="perm_read" />
        <field eval="0" name="perm_create" />
    </record>
```

In this case, he/she will keep seeing the document he/she was in the reviewer table. Not sure, this is suitable.

**Comment by LoisRForgeFlow** [comment]
> Opinion,
> 
> If we don't want to fix in the core code (models.py), to allow such thing. We will need to add security rule like this to the model in `<models>_tier_validation`
> 
> ```
>     <record id="ir_rule_<model>_allowed_reviewers" model="ir.rule">
>         <field name="model_id" ref="model_<mode>" />
>         <field name="domain_force">[('review_ids.reviewer_ids', 'in', [user.id])]</field>
>         <field name="name">Budget Request Tier Reviewer</field>
>         <field name="groups" eval="[(4, ref('base.group_user'))]" />
>         <field eval="0" name="perm_unlink" />
>         <field eval="0" name="perm_write" />
>         <field eval="1" name="perm_read" />
>         <field eval="0" name="perm_create" />
>     </record>
> ```
> 
> In this case, he/she will keep seeing the document he/she was in the reviewer table. Not sure, this is suitable.

Exactly, that was going to be my response. You should define that rule in your implementation.

I think in most of the cases the reviewers will be people with read access at least. If there are other rules preventing someone to see a record, I would not always want to grant them access because of a tier review (maybe this person is part of a really big group and this document is not really for them, or maybe the tier definition was wrong). Therefore, I tend to think that by default we should keep as is now, but I agree, in your particular case, the security rule you propose looks like the solution for me.

My 2 cents :)

**Comment by kittiu** [comment]
Thanks so much, @LoisRForgeFlow for sharing your opinion. OK, I think it is not yet justified to add the new feature. I shall close this.
