### ISSUE TITLE
[14.0]date_range: problem during installation

### ISSUE THREAD

**Issue by chusamo** [OCA/server-ux#416]
## Describe the bug
This module creates a ir.cron action. When a ir.cron its created Odoo automatically creates a ir.action.server related with it.
There is a field in ir.action.server called activity_user_type it's requiered and has a default value.

It's seems that is not taking the default value on the instalation of this module.

![Captura de pantalla de 2021-12-02 13-00-21](https://user-images.githubusercontent.com/31690536/144418279-d4cd5087-c865-4981-924f-783710fdf61b.png)

I've installed succesfully others modules with an ir.cron in the data.xml.

## To Reproduce
**Affected versions**:

1. Clic on Install

**Comment by HaraldPanten** [comment]
Hi @chusamo are you sure that this is an issue of the module? or is this issue related to any special configuration of your Odoo instance?

We have installed the module in several projects (V14) and we didn't have any issue. And it has been installed in runbot without any issue as well.

Regards.

**Comment by chusamo** [comment]
> Hi @chusamo are you sure that this is an issue of the module? or is this issue related to any special configuration of your Odoo instance?
> 
> We have installed the module in several projects (V14) and we didn't have any issue. And it has been installed in runbot without any issue as well.
> 
> Regards.

Indeed, our odoo "base" module was outdated. Now it works.  Thank you for your reply
