### ISSUE TITLE
[IMP] mass_operation_abstract: Improve README

### ISSUE THREAD

**Issue by rousseldenis** [OCA/server-ux#439]
@legalsylvain Is it possible to improve README to give examples of implementing it on new modules?

**Comment by legalsylvain** [comment]
Hi. This module is obsolete. I was developped it because i didn't know actions servers.

See : https://github.com/OCA/server-ux/pull/97#discussion_r346850594

**Comment by rousseldenis** [comment]
> Hi. This module is obsolete. I was developped it because i didn't know actions servers.
> 
> See : [#97 (comment)](https://github.com/OCA/server-ux/pull/97#discussion_r346850594)

Ok, so this module could be taken as is (with some adaptations to target version):

https://github.com/OCA/sale-workflow/tree/7.0/sale_order_mass_action

**Comment by legalsylvain** [comment]
Indeed.
