### ISSUE TITLE
[15.0] Base tier validation - Incorrect: The operation is under validation.

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/server-ux#473]
## Module
base_tier_validation

## Describe the bug
def write is inherited to check for state changes, one of the checks is: 
`and not vals.get(self._state_field) in (self._state_to + [self._cancel_state])`

If vals doesn't contain state the warning is shown.

I suggest adding a check to see if the write should be validated, something like:
```
            if (
                rec.review_ids
                **and self._state_field in vals**
                and getattr(rec, self._state_field) in self._state_from
                and not vals.get(self._state_field) in (self._state_to + [self._cancel_state])
                and not rec._check_allow_write_under_validation(vals)
            ):
                raise ValidationError(_("The operation is under validation."))
```

**Comment by vincent-cowboy** [comment]
Experiencing the same issue ; adding `and self._state_field in vals` as suggested solves it.
