### ISSUE TITLE
[14.0] base_export_manager disable export don't work

### ISSUE THREAD

**Issue by ygol** [OCA/server-ux#474]
unable to re-open #57 so copying it to a new issue

## Module
base_export_manager

## Describe the bug
disable export don't work

## To Reproduce
**Affected versions**: 14.0

## Steps to reproduce the behavior:
1.Activate the developer mode
2.Go to Settings > Users > Groups to select a user group
3.Edit the group and go to the Access Rights tab
4.Uncheck the "Export Access" box on the object of your choice and save
5.Connect as a user of this group
6.Go to the list view of the object you disabled the export but The "Export" is still there.

**Expected behavior**
no "Export" option shown

**Comment by nicomacr** [comment]
@ygol I fix this problem here https://github.com/OCA/server-ux/pull/478 over v15, if you want, you can test it there in runbot build.

**Comment by ygol** [comment]
hi @nicomacr thanks for your reply.
Here's what I tried:
1. I changed the configuration for the lead/opportunity accesses:
![image](https://user-images.githubusercontent.com/2945174/162214929-e5bd9bd2-e557-440b-a968-f535657cd56c.png)

2. I still can access the export option:
![image](https://user-images.githubusercontent.com/2945174/162215013-b7a899d2-d5ba-4c73-90f1-abfbd99f622f.png)

Did I miss something?
Best.

**Comment by nicomacr** [comment]
> hi @nicomacr thanks for your reply. Here's what I tried:
> 
> 1. I changed the configuration for the lead/opportunity accesses:
>    ![image](https://user-images.githubusercontent.com/2945174/162214929-e5bd9bd2-e557-440b-a968-f535657cd56c.png)
> 2. I still can access the export option:
>    ![image](https://user-images.githubusercontent.com/2945174/162215013-b7a899d2-d5ba-4c73-90f1-abfbd99f622f.png)
> 
> Did I miss something? Best.

@ygol yes, the user in  this case "Admin" have the General settings "Manager" because of that you still see the option. Try with different user or change that right.

**Comment by ygol** [comment]
hmm sorry if I don't understand. I removed the export flag for anyone regarding this model. 
What/where is the general settings "Manager"?

![image](https://user-images.githubusercontent.com/2945174/162223583-3c4e3627-dc06-4483-8f86-081d14838f0f.png)

**Comment by nicomacr** [comment]
@ygol in the user settings, change for "Access Rights" instead of "Settings"
![Screenshot (1)](https://user-images.githubusercontent.com/7657373/162225742-2986be04-5b0a-48ce-a2c0-2eda9d2f1a31.png)
