### ISSUE TITLE
Base tier validation: Send notifications according to approval sequence

### ISSUE THREAD

**Issue by florenciafrigieri2** [OCA/server-ux#480]
**Is your feature request related to a problem?**
Is not a problem itself, but an improvement. 

**Describe the solution you'd like**
The need is to notify the approvers when they have the purchase order, sales orders, etc., ready to approve/reject. 

**Describe alternatives you've considered**
Currently, there's a checkbox that allow to notify all the approvers when the validation is triggered. But if there's a approval sequencial, the following approvers does not received a notification when it's their turn to revise the request.

**Additional context**

**Comment by BT-mfasola** [comment]
we would actually like to do the same.
suggestion:
- add a state 'waiting' to reviews for those who are pending but not next in sequence
- => this way not only the notification could be improved, but also the report in the dashboard
thoughts?
