### ISSUE TITLE
base_tier_validation_server_action: Execute action after the write() on record.

### ISSUE THREAD

**Issue by rousseldenis** [OCA/server-ux#493]
@kittiu I think there is a limitation in the behaviour doing the trigger of the action on reviews write() as the actual record is not still really written at that time. Therefore, we cannot rely on record values (that are in the write vals) to filter the action records.

I will propose a hook method in the write method in order to trigger the server action just after the super() call, there:

https://github.com/OCA/server-ux/blob/14.0/base_tier_validation/models/tier_validation.py#L283

What do you think ?

**Comment by kittiu** [comment]
I agree 👍
