### ISSUE TITLE
[base_tier_validation] BAD PERFORMANCE to compute and search field rejected

### ISSUE THREAD

**Issue by celm1990** [OCA/server-ux#496]
## Module
base_tier_validation
## Describe the bug
On Database with more than 80K records, at open sidebar and click Pending Reviews is very very slow
![image](https://user-images.githubusercontent.com/7775116/168171237-4e67697f-6202-4fe4-88d5-cd11f1f52911.png)

## To Reproduce
**Affected versions**:
All, I tested on V13
- on SideBar click to open pending records this call to search with domain [[["can_review", "=", true]]](https://github.com/OCA/server-ux/blob/13.0/base_tier_validation/static/src/js/systray.js#L147) 

![image](https://user-images.githubusercontent.com/7775116/168171403-c8fb08c8-551b-474a-bf97-3594d1e74d64.png)

- `can_review `is field  `computed `and implement [search function](https://github.com/OCA/server-ux/blob/13.0/base_tier_validation/models/tier_validation.py#L90), field `rejected ` is also computed and implement [search funcion](https://github.com/OCA/server-ux/blob/13472458f3897daf995c1ca99fa5c4e4cbbe0586/base_tier_validation/models/tier_validation.py#L121-L127) 
for `sale.order` this function search is done with state ["draft", "sent", "to approve"](https://github.com/OCA/sale-workflow/blob/3883f38a79a725acc58ee57b90b3944fe03b0aa1/sale_tier_validation/models/sale_order.py#L10)
On my case search is done with 30K records approx, but when use filtered for field `rejected `is where is more slower see [_compute_validated_rejected](https://github.com/OCA/server-ux/blob/13472458f3897daf995c1ca99fa5c4e4cbbe0586/base_tier_validation/models/tier_validation.py#L171-L175)

![image](https://user-images.githubusercontent.com/7775116/168172765-6c70c7e2-455f-49d0-95a0-e23abfd05815.png)

**Expected behavior**
Better performance at search records, fields computed not storable is very slower

Optimize _compute_validated_rejected and use SQL on some cases(if possible)
Try convert Fields to store=True

Optimize _search_can_review
![image](https://user-images.githubusercontent.com/7775116/168180872-ea39dd49-795f-4125-a0a7-7574bb27dccc.png)

https://user-images.githubusercontent.com/7775116/168182672-122d4b31-52c8-4d14-b42b-1103794371b3.mp4

**Comment by rousseldenis** [comment]
Indeed, this has to be improved.

If I have time, I will try to fix it

**Comment by bosd** [comment]
@rousseldenis Is there already an PR for this?
