### ISSUE TITLE
[RFC] refactoring mass_editing and change repo

### ISSUE THREAD

**Issue by legalsylvain** [OCA/server-ux#539]
hi all,

**Rational**
- ``mass_editing`` is a OCA module that exists for years in OCA/server-ux. 
- In the meantime OCA/server-backend receive some new module ``server_action_navigate`` ([here](https://github.com/OCA/server-backend/tree/14.0/server_action_navigate)), ``server_action_sort`` ([here](https://github.com/OCA/server-backend/pull/70)). (But not ``server_action_domain`` that is in ``server-ux``)

**Proposal** 
- move the module ``mass_editing`` and ``server_action_domain`` from server-ux to server-backend to have all the modules in the same place. (or the reverse).
- finally, rename module (``mass_editing`` -> ``server_action_edit``) and models.

**Improvements**
- all modules in the same place
- better technical name that correspond to the new structure.

CC : @SerpentCS, @ivantodorovich, @JayVora-SerpentCS

Thanks for your comments.

**Comment by ivantodorovich** [comment]
I agree with you, makes sense to do that.
As for the server module I suggest `server_action_mass_edit`

**Comment by legalsylvain** [comment]
Thanks for your answer. 
question : all modules in OCA/server-ux or all modules in OCA/server-backend ? 

I must confess that description of each repo are very synthetic :-)
- https://github.com/oca/server-ux#server-ux  ``None``
- https://github.com/OCA/server-backend/#server-backend ``TODO: add repo description.``.

I'm in favor of all in OCA/server-ux but not a blocking point.

**Comment by ivantodorovich** [comment]
`server-ux` makes sense IMO, as these modules offer usability improvements afterall, it's ux related
