### ISSUE TITLE
15.0 base_tier_validation: Approval sequence is backwards

### ISSUE THREAD

**Issue by BT-jmichaud** [OCA/server-ux#546]
## Module
base_tier_validation
To test the behavior, you can test with [purchase_tier_validation](https://github.com/OCA/purchase-workflow)

## Describe the bug
When validation reviews are created, they are supposed to be created in the same order as the sequence was defined. But here it seems that the sequence taken is backward. It results in that the review are not done in the correct sequence.
Of course the workaround is to create the tier validation by reversing the values of the sequence.

This probably comes from the 'order="sequence desc"' used here: https://github.com/brain-tec/server-ux/blob/25303fa7c97840520c3fc84471593dcdb4f43c07/base_tier_validation/models/tier_validation.py#L412

## To Reproduce
**Affected versions**: 14.0 and 15.0

1. Install also [purchase_tier_validation](https://github.com/OCA/purchase-workflow) or another implementation.
2. Create a tier definition with 1 as sequence and the value "true" for the field "Approve by Sequence".
3. Create a tier definition with 2 as sequence and the value "true" for the field "Approve by Sequence".
4. Create the document (in my case a purchase order) that needs validation.
5. Request the validation and check the reviews
6. You will see that the review placed in the first place is not the one that you defined in your definition.

**Expected behavior**
The sequence of tier validation should be respected.

**Additional context**
NA

**Comment by evanomnisoft** [comment]
Seems like sequence acts more like a "weightage" instead since largest values go first. Perhaps, since the default value is set to 30, this was the actual intention of the code?
