### ISSUE TITLE
Add domain field

### ISSUE THREAD

**Issue by SAMSA-IT** [OCA/server-ux#559]
**Is your feature request related to a problem?**
I can tick "Apply domain" but I cannot enter the domain.
![grafik](https://user-images.githubusercontent.com/24456505/204083608-368881d7-660a-44b7-81e2-b4718ad3aa15.png)

**Describe the solution you'd like**
An additional colum called "Domain" in which I can enter the domain.
Then this domain could be applied to prevent unwanted changes.

**Comment by legalsylvain** [comment]
That is not the objective of this field.
