### ISSUE TITLE
[v14 base_tier_validation, base_tier_validation_formula], not possible to entry reviewer expression other than rec.env.user, is it a bug or only eupport rec.env.user?

### ISSUE THREAD

**Issue by bunhin** [OCA/server-ux#568]
module : base_tier_validation_formula
version : 14.0

I am not sure whether it is a bug, or an error in my expression syntax, or a current feature,  but it seems not possible to enter and save any reviewer expression (other than the default  "rec.env.user") when creating tier definition and to choose python expression for the reviewer.

I did searching a lot for a sample of the usable syntax but not found any.

I try to entry tier definition with a dynamic reviewer using python expression, for a use case example:  
sales order document, the reviewer I want is the one in the same sales_team with the user creating the sales order, and having job position name contains Supervisor.  
 
Anyone, please give information. Thank you.

**Comment by LoisRForgeFlow** [comment]
Hi @bunhin 

The expressions expects a res.users record as result. Your expression is likely not doing so, if you want more specific help, please share the expression you are using.

Regards,

**Comment by bunhin** [comment]
Hi @LoisRForgeFlow , Thank you for your kind response.

Actually i want to return  users that is (are) in the sales_team used in the Sales Order Instance that has job position like Supervisor:

something like:

sales_team_members = rec.team_id.member_ids
all_spv = env["hr.job"].filtered(lambda s: "Supervisor" in s.name)
team_spv = all_spv.filtered(lambda l: l.id in team_members)
review_user = team_spv.user_id

But I am not sure whether it is possible? or need to wrap the code in a function?

**Comment by LoisRForgeFlow** [comment]
Just in case, I tested the functionaltity with a simple expression on runboat and everything is working fine.

In your code at a first glance, hr.job does not seem to have a user_id field, so it seems incorrect. EDIT: to give you a clearer hint: `team_spv = all_spv.filtered(lambda l: l.id in team_members)` is returning a hr.job recordset not a team, this might be your issue.

As this is no longer a bug but rather a seek for help, I am closing the issue if you don't mind. I suggest that you contact your Odoo integrator to get help creating the expression or use the forums and mailing lists.
