### ISSUE TITLE
base_export_manager  disable export don't work

### ISSUE THREAD

**Issue by SmithLin0618** [OCA/server-ux#57]
i have do as configuration as below：

1.Activate the developer mode
2.Go to Settings > Users > Groups to select a user group
3.Edit the group and go to the Access Rights tab
4.Uncheck the "Export Access" box on the object of your choice and save
5.Connect as a user of this group
6.Go to the list view of the object you disabled the export

but The "Export" is still there.

**Comment by ygol** [comment]
Same behaviour tested for version 14.0 this module doesn't seems to work.

[ Isn't it a problem that the bot automatically closes bug report?! ]
