### ISSUE TITLE
[15.0] date_range: Ranges not displayed on date/datetime type filters

### ISSUE THREAD

**Issue by ao-landoo** [OCA/server-ux#597]
Since module date_range was migrated to version 15.0 date.range model registers are not displayed as filters for fields that are of type Date/Datetime.

In order to reproduce the behavior:
1- Go to Technical -> Date Range Types and create a register, for instance name = "MONTH"
2- Go to Technical -> Date Range and create a register, for instance type "MONTH" and from 1-feb to 28-feb
3- Go to sales order list view, and try to filter by create date
4- It's not allowing to filter by MONTH date range, it's not appearing

It's working fine on runboat 14.0

![Captura de pantalla de 2023-02-14 17-02-48](https://user-images.githubusercontent.com/74420754/218791645-e84c29b3-7c42-4905-a759-8fdaa46c11c0.png)

@JoanMForgeFlow I'm mentioning you as you're who migrated it. Any idea what could be wrong?

**Comment by pedrobaeza** [comment]
@JoanMForgeFlow can you please check that missing bits from the migration?

**Comment by alan196** [comment]
I have the same issue, I have tested in my local with Odoo and OCB, and also tested in this [runboat](http://oca-server-ux-15-0-21ec89416d3b.runboat.odoo-community.org/)

**Comment by RadjaCyb** [comment]
> Since module date_range was migrated to version 15.0 date.range model registers are not displayed as filters for fields that are of type Date/Datetime.
> 
> In order to reproduce the behavior: 1- Go to Technical -> Date Range Types and create a register, for instance name = "MONTH" 2- Go to Technical -> Date Range and create a register, for instance type "MONTH" and from 1-feb to 28-feb 3- Go to sales order list view, and try to filter by create date 4- It's not allowing to filter by MONTH date range, it's not appearing
> 
> It's working fine on runboat 14.0
> 
> ![Captura de pantalla de 2023-02-14 17-02-48](https://user-images.githubusercontent.com/74420754/218791645-e84c29b3-7c42-4905-a759-8fdaa46c11c0.png)
> 
> @JoanMForgeFlow I'm mentioning you as you're who migrated it. Any idea what could be wrong?

Hello,

Did you find any solution please ?

**Comment by RadjaCyb** [comment]
> I have the same issue, I have tested in my local with Odoo and OCB, and also tested in this [runboat](http://oca-server-ux-15-0-21ec89416d3b.runboat.odoo-community.org/)

Did you find any solution please ?
