### ISSUE TITLE
[12.0-mass_editing] Do not work on message_partner_ids (followers)

### ISSUE THREAD

**Issue by cvinh** [OCA/server-ux#61]
Tested on Runbot today
Steps to reproduce :
- add message_partner_ids field in mass editing setup for sale_order object
- use mass_editing on sale order object (try to Add, Remove or Set option)

Result : 
- The message_partner_ids field remains unchanged
Expected result : 
- The message_partner_ids field should be edited

**Comment by pedrobaeza** [comment]
That's because that field is somewhat special and require to call a method called something similar to `subscribe`. It's not a problem of `mass_editing` per se.

**Comment by cvinh** [comment]
@JayVora-SerpentCS do you have a hint on that one ?
Thanks in advance

**Comment by JayVora-SerpentCS** [comment]
@cvinh On our internal commits, we've https://github.com/JayVora-SerpentCS/MassEditing/commit/97b326e923279c3e19ceffc023a0ff3142396045 to manage this.
Check plz.
