### ISSUE TITLE
[16.0] base_revision "no create method in batch" warning spam

### ISSUE THREAD

**Issue by auroraeosrose** [OCA/server-ux#639]
## Module
base_revision

## Describe the bug
Every time a worker starts the following shows up in the logs

```
2023-04-19 13:31:51,787 181484 WARNING odoo_db odoo.api.create: The model odoo.addons.base_revision.models.base_revision is not overriding the create method in batch
```

## To Reproduce

1. Install base_revision 
2. Start odoo with workers
3. View logs

**Expected behavior**
@api.model is apparently now angry and wants to be always @api.model_create_multi

**Additional context**
https://github.com/odoo/odoo/blob/40596ed1eccdf0f37b4fa3a8a337e7a7cc3461ce/odoo/api.py#L393

https://github.com/odoo/odoo/pull/80824

**Comment by CRogos** [comment]
Could you have a look on https://github.com/OCA/server-ux/pull/672

**Comment by auroraeosrose** [comment]
That PR looks good to me!

**Comment by CRogos** [comment]
Could you add a review on the PR?
![image](https://github.com/OCA/server-ux/assets/1799080/5f0f6a90-1344-43ad-ad30-c320de2c77f6)
