### ISSUE TITLE
[V16.0 ] upgrade base_menu_visibility_restriction from V15 to V16

### ISSUE THREAD

**Issue by SAMSA-IT** [OCA/server-ux#653]
Hello,
is there a plan to upgrade base_menu_visibility_restriction from V15 to V16?
Thanks for any infos.
Best regards,
Manuel

**Comment by pedrobaeza** [comment]
Please check a bit before asking:

https://github.com/OCA/server-ux/pull/622

**Comment by SAMSA-IT** [comment]
Sorry, you are right. Thanks for the info.
