### ISSUE TITLE
[16.0] date_range: Ranges not displayed on date/datetime type filter

### ISSUE THREAD

**Issue by TimGlimmerveen-360ERP** [OCA/server-ux#660]
## Module
date_range

## Describe the bug
Ranges are not displayed.

## To Reproduce
1- Go to Technical -> Date Range Types and create a register, for instance name = "MONTH"
2- Go to Technical -> Date Range and create a register, for instance type "MONTH" and from 1-feb to 28-feb
3- Go to sales order list view, and try to filter by create date
4- It's not allowing to filter by MONTH date range, it's not appearing

**Comment by pedrobaeza** [comment]
Duplicated of #597
