### ISSUE TITLE
[11.0-mass_editing] missing field labels

### ISSUE THREAD

**Issue by Martronic-SA** [OCA/server-ux#68]
I've added a mass editing template for product.template and in the mass_editing wizard all the field labels are missing except for the many2many fields where there is a separator tag.
Is that something you encounter also?

**Comment by pedrobaeza** [comment]
Screenshot?

**Comment by Martronic-SA** [comment]
Sorry my module was probably not up to date.
I downloaded again and it's ok now.

**Comment by Martronic-SA** [comment]
![23-05-2019 10-24-40](https://user-images.githubusercontent.com/6492010/58237303-17619f80-7d45-11e9-9a40-acd4fb463492.jpg)

**Comment by Martronic-SA** [comment]
Ok the problem apprears when you add a field of type many2many

**Comment by Martronic-SA** [comment]
The problem seems to come when there is a group tag added inside the main group tag in the form which is the case with many2many and text. If you confirm the issue I can submit a pr for fixing that.

**Comment by pedrobaeza** [comment]
Can you please submit the fix?

**Comment by Martronic-SA** [comment]
Here we go: [https://github.com/OCA/server-ux/pull/78](https://github.com/OCA/server-ux/pull/78)

**Comment by Martronic-SA** [comment]
I haven't tested on Odoo 12 but wouldn't be suprised if there is the same issue

**Comment by gr22** [comment]
> I haven't tested on Odoo 12 but wouldn't be suprised if there is the same issue

I can confirm same problem with v12. I applied the patch from V11 as a quick fix
https://github.com/OCA/server-ux/pull/78/commits/d899e8d4be3aaa3845d481c5e0967e4e5fca2ead
