### ISSUE TITLE
date_range module published on odoo shop has AGPL-3 license

### ISSUE THREAD

**Issue by jerzyk** [OCA/server-ux#700]
date_range module her (on OCA gothub) has LGPL-3 license vs module published on odoo shop has AGPL-3

**Comment by legalsylvain** [comment]
Hi @jerzyk. We don't manage odoo shop. The OCA references the OCA github repo only. Then the data are fetched. If there are some errors in apps.odoo.com. (and indeed, here, [the value looks incorrect](https://apps.odoo.com/apps/modules/16.0/date_range/), please contact odoo team)

Kind regards.

Closing. Feel free to reopen, if you think OCA can do something.

**Comment by jerzyk** [comment]
ok, so the module description on apps.odoo.com should be fixed, because it point to here...
I'will write email to maintainers.
