### ISSUE TITLE
Adding batch for server_action_mass_edit

### ISSUE THREAD

**Issue by sefirosweb** [OCA/server-ux#707]
**Describe the solution you'd like**
It is possible to create a batch request when update info? if you need to update a hundred of rows this can be stopped if you have an max time execution,
This can be resolve easy send request in chunks of 100 rows, the max number can be changed depends of model, the max value can be added in config:
![image](https://github.com/OCA/server-ux/assets/20754836/6f36e45c-436d-4cb8-98ad-2018c2df054d)

**Additional context**
This is the same when you upload a csv file you can set the max batch

**Comment by legalsylvain** [comment]
Hi. 
thanks for your proposal. IMO that is not related to server_ation_mass_edit. You can face this issue for all the server actions. 
so, i think the correct design should be to develop a new module, named server_action_batch that could work for all the server actions
What do you think ?

**Comment by sefirosweb** [comment]
Yes, it seems that it makes more sense, it can be more useful

**Comment by legalsylvain** [comment]
OK ! closing this issue. if you propose a module, please ping me.

regards.
