### ISSUE TITLE
base_tier_validation: Missing field "need_validation" in form-embedded lists

### ISSUE THREAD

**Issue by houzefa-abba** [OCA/server-ux#825]
Hi here is an issue when a model plugged to `base_tier_validation` is displayed as a list in another form: when clicking a record in such a list, the view crashes:
> Error: Missing field string information for the field 'need_validation' from the 'res.partner' model

An easy way to test this is from [a partner-contact runboat](https://runboat.odoo-community.org/webui/builds.html?repo=OCA/partner-contact&target_branch=16.0):
* open contacts, switch to list view
* select 2 contacts > Action > Merge (standard Odoo feature)
* in the merge wizard, click on a partner

➔ Screenshot:
![Screenshot at 2024-02-14 17-39-21](https://github.com/OCA/server-ux/assets/6347423/45f15038-e6c8-43aa-9ac9-44ffb0e5e15d)

This isn't specific to that model nor to that wizard; I can also reproduce from [a sale-workflow runboat](https://runboat.odoo-community.org/webui/builds.html?repo=OCA/sale-workflow&target_branch=16.0) in a more convoluted way:
* create a quotation, sell a product tracked via serial number (eg "Drawer")
* open that serial number (lot) form within Inventory
* edit view to remove invisibility condition on the `sale_order_ids` field
* click on a sales order

➔ Screenshot:
![Screenshot at 2024-02-14 17-40-19](https://github.com/OCA/server-ux/assets/6347423/32328eb2-7819-457f-8a7d-ce7cce151f13)

**Comment by tugsbayarg** [comment]
You have to add need_validation field with invisiblity=1 in form view. To add field into view you need to inherit main form view and add field into inherited form view

**Comment by houzefa-abba** [comment]
> You have to add need_validation field with invisiblity=1 in form view. To add field into view you need to inherit main form view and add field into inherited form view

Hi that indeed seems to be what's missing; the issue here is `base_tier_validation` users never added that so far (eg [in `sale_tier_validation`](https://github.com/OCA/sale-workflow/blob/16.0/sale_tier_validation/views/sale_order_view.xml)).

Adding it by hand in each derived module seems cumbersome to me; especially when talking about modals such as that partner merge one which may well define their own views.

I think the assumption so far was that the mixin provided by `base_tier_validation` would inject these fields, same as it already injects some UI elements such as validation buttons.
