### ISSUE TITLE
[12.0][ADD] any module to allow hiding print menu based on context passed in action?

### ISSUE THREAD

**Issue by Saran440** [OCA/server-ux#85]
I would like to create new module "report_hide_menu_by_context". Objective is to hide report action based on value in context. For example, when click on Customer Invoice menu, with context type='out_invoice', this should hide vendor bill form and show only customer invoice form.

Is this kind of module already exists? Any idea/suggestion?

**Comment by kittiu** [comment]
Hi, may I ask some technical question.

By doing the above, we will need to inherit **fields_view_get()** at the very base module odoo.models.py
```
@pycompat.implements_to_string
class BaseModel(MetaModel('DummyModel', (object,), {'_register': False})):
```
Anyone can suggest how to do this?
