### ISSUE TITLE
[16.0][base_tier_validation] Make "full" form readonly optional

### ISSUE THREAD

**Issue by intero-chz** [OCA/server-ux#877]
**Is your feature request related to a problem?**
With https://github.com/OCA/server-ux/commit/d67a23d833787ecbefac222c83e8a499f045eaea#diff-5b72a073de187894d5d5401d6574d08eb57b1fcf07fcaa0ad1682b09dd65bc65 every non excepted field in a form view of a tier validation implementing model becomes readonly if reviews are existing on the record.

IMO that's a big change to the previous version.

**Describe the solution you'd like**
The feature is basically very good. But it is probably not needed in every environment and takes away some flexibility from the module in terms of independent extensions.

It would be desirable if the read-only setting of the fields could be changed via a `tier.validation` method for each implementing model.

**Describe alternatives you've considered**
Another solution or probably a thing to do anyway is to divide the whole `get_view` method into submethods.

**Comment by intero-chz** [comment]
For me that's solved with https://github.com/OCA/server-ux/commit/451780ae5b04fd5b14aa26c4dc03a0a4a14dbf52

Thanks @Kev-Roche

**Comment by Kev-Roche** [comment]
Ho sorry, did not see your issue before. Your welcome, thanks !
