### ISSUE TITLE
[12.0][Question] base_tier_validation: dynamic tiers validation possible?

### ISSUE THREAD

**Issue by kittiu** [OCA/server-ux#88]
@lreficent @jbeficent first of all, thank you for this fabulous modules,
I have tested also with base_tier_validation_formula which allow it to by dynamically select documents and users to approve, which is really great.

What if we don't know in advance, how many tiers it should have for validation? For dept A, 2 steps, for dept B 4 steps. Or when it need to go through org chart of HR levels.

How to cope with this?

**Comment by JordiBForgeFlow** [comment]
Each tier should be in a different tier definition. A purchase order can
trigger multiple parallel validations, based on separate definitions.


For example, approver A should approve PO's between 5000 and 1000.

Approver B should approve PO's over 1000.


The a PO for 25000 would trigger 2 validations, for approver A and B.

**Comment by kittiu** [comment]
@jbeficent thank you for your answer. I think I do get that.
My question is more like, when organization has chain of command (can be separated table), and different department has different hierarchical level which can lead to different number of steps to validate.

Also, I saw your implement with simple Yes/No, which already cover many use cases. My real life requirement is a little more nasty by having,
* Yes/No with comments
* Send to another person for comment (which may insert new validation step during process)
* Some kind of sequence (Mr. A before Mr. B, this I think we can do already with formulas?)

Anyway, I admit I didn't try it deeply yet, I will and will come back to discuss more :)

**Comment by kittiu** [comment]
@jbeficent @lreficent 
cc @ps-tubtim 
From the 1st requirement, Yes/No with comments where,
* On the tier validation setup, we can mark which validation to also have comment
* When click the green "Validate" button, then pop up "Comment" dialog
* User fill in comment and confirm, the Reviews table below also have new column "Comment"

If I am to try this, should this be included in base_tier_validation or should be separated addon, i.e., base_tier_validation_comment
WDYT?

**Comment by JordiBForgeFlow** [comment]
@kittiu I would include that in base_tier_validation, as it can be activated as an option @lreficent

**Comment by kittiu** [comment]
Thank you!, @ps-tubtim let's start working on it as PR, improvement to base_tier_validation.

**Comment by hitrosol** [comment]
Hi, would it be possible to show the person / group user who will approve the document? Currently, the user only know the person after he/she approve it in the column Done by. If we have that information then the requester can chase the person whenever the document hasn't been approved yet.

![image](https://user-images.githubusercontent.com/5949936/66255380-ef7f4f80-e7ac-11e9-9a97-51aad5af3379.png)

**Comment by LoisRForgeFlow** [comment]
@hitrosol We decided to remove that in favor of the description as the different possibilities would force to show several columns (user, group or dinamic with python), if your users needs to know who are in charge of validation just extend the description with something like "to be reviwed by someone or some group".
