### ISSUE TITLE
[17.0][base_tier_validation] Some modules have inconsistent states, some dependencies may be missing: ['base_tier_validation']

### ISSUE THREAD

**Issue by xantocoder** [OCA/server-ux#893]
## Module
base_tier_validation  17.0.1.0.0
## Describe the bug
when insall the [base_tier_validation] module, the server log shows the following statement:
 Some modules have inconsistent states, some dependencies may be missing: ['base_tier_validation']

## To Reproduce
**Affected versions**:
17.0 (other versions not tested)
1. install the base_tier_validation module 
2.
3.

**Expected behavior**
the base_tier_validation module installed successfully

**Additional context**
Ubuntu 22.04 python 3.10.12

**Comment by pedrobaeza** [comment]
This is because you haven't deployed the module correctly, but nothing related with the module itself. Please go to forums to ask for assistance giving details on how you installed it. 

Closing this.

**Comment by xantocoder** [comment]
> This is because you haven't deployed the module correctly, but nothing related with the module itself. Please go to forums to ask for assistance giving details on how you installed it.
> 
> Closing this.
Thanks for your quick reply. 
I am so sorry that I am a beginer of the odoo system. But I am curious that the error message still exists when I install from the app. I'll ask this in the forum. Thanks again.
